# Pre-commit Configuration for Claude Development Framework
# Install: pre-commit install
# Run manually: pre-commit run --all-files
# Bypass (emergency only): git commit --no-verify

repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # File checks
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: detect-private-key

      # Formatting
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']

      # Python specific
      - id: check-ast
      - id: check-docstring-first
      - id: debug-statements

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11
        args: ['--line-length=100']

  # Python linting
  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        args: ['--errors-only']
        exclude: '^tests/'

  # Python type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ['--ignore-missing-imports', '--no-error-summary']
        additional_dependencies: ['pydantic']
        exclude: '^tests/'

  # Framework-specific hooks (local)
  - repo: local
    hooks:
      # No TODO comments in source code
      - id: no-todos
        name: Block TODO comments
        entry: python tools/pre-commit-hooks/check-no-todos.py
        language: system
        types: [python]
        exclude: '^(tests/|docs/)'
        pass_filenames: true

      # Spec alignment check
      - id: spec-alignment
        name: Check spec-code alignment
        entry: python tools/pre-commit-hooks/check-spec-alignment.py
        language: system
        pass_filenames: false
        always_run: true

      # Test coverage threshold
      - id: coverage-threshold
        name: Check test coverage
        entry: python tools/pre-commit-hooks/check-coverage-threshold.py
        language: system
        pass_filenames: false
        always_run: true

      # Test-first enforcement
      - id: test-first
        name: Enforce test-first development
        entry: python tools/pre-commit-hooks/check-test-first.py
        language: system
        types: [python]
        exclude: '^(tests/|docs/|scripts/)'
        pass_filenames: true

      # ADR references
      - id: adr-references
        name: Validate ADR references
        entry: python tools/pre-commit-hooks/check-adr-references.py
        language: system
        types: [python]
        pass_filenames: true
